# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 8083   # HTTP (Tomcat) port

spring:
  application:
     name: gateway-def

info:
    component: Zuul Server test

zuul:
  ignoredServices: '*'
  routes:
    hello-web-service-hello-word:
      path: /hello-web/**
      url: http://localhost:8080
#      serviceId: hello-web
      stripPrefix: false
      sensitiveHeaders:
    uaa-service:
      sensitiveHeaders:
      path: /uaa/**
      url: http://localhost:8087
#      serviceId: uaa
      stripPrefix: false
    hello-word:
      sensitiveHeaders:
      path: /hello-word/**
      url: http://localhost:8081
#      serviceId: uaa
      stripPrefix: false

#http://stackoverflow.com/questions/28904247/zuul-timing-out-in-long-ish-requests
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false