spring:
  application:
     name: hello-web
  thymeleaf:
    mode: LEGACYHTML5

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    homePageUrlPath: ${server.contextPath}/
    statusPageUrlPath: ${server.contextPath}/info
    healthCheckUrlPath: ${server.contextPath}/health

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port
  contextPath: /hello-web
  use-forward-headers: true

security:
  oauth2:
    client:
      clientId: acme
      clientSecret: acmesecret
      accessTokenUri: http://localhost:8083/uaa/oauth/token
      userAuthorizationUri: http://localhost:8083/uaa/oauth/authorize
    resource:
      userInfoUri: http://localhost:8083/uaa/me